apiVersion: v2
appVersion: v0.4.0
description: A Helm chart for a sample RAG application that showcases multimodal usecases using NVIDIA AI Foundation Models endpoints with LangChain connectors.
name: rag-multimodal-app
type: application
version: v0.4.0
